[workspace.package]
version = "0.0.1"
authors = [
    "James Hodgkinson <james@terminaloutcomes.com>",
    ]
rust-version = "1.66"
edition = "2021"
license = "MPL-2.0"
homepage = "https://github.com/yaleman/ocsf/"
repository = "https://github.com/yaleman/ocsf/"

[workspace]
members = [
    "ocsf-codegen",
    "ocsf",
]