/// Windows Resource Activity events report when a process accesses a Windows managed resource object, successful or otherwise.
///
/// Sourced from: `events/events/system/windows/resource.json`
#[derive(serde::Deserialize, serde::Serialize)]
pub struct ResourceActivity {
    pub activity_id: Option<String>,
    pub win_resource: String,
}

impl ResourceActivity {
    pub const UID: u16 = 10;
}

/// Registry Key Activity events report when a process performs an action on a Windows registry key.
///
/// Sourced from: `events/events/system/windows/registry_key.json`
#[derive(serde::Deserialize, serde::Serialize)]
pub struct RegistryKeyActivity {
    pub access_mask: Option<String>,
    pub activity_id: Option<crate::RegistryKeyActivity>,
    /// The actor that performed the activity on the `reg_key` object.
    pub actor: String,
    pub create_mask: Option<String>,
    pub open_mask: Option<String>,
    pub prev_reg_key: Option<String>,
    pub reg_key: String,
}

impl RegistryKeyActivity {
    pub const UID: u16 = 8;
}

/// Registry Value Activity events reports when a process performs an action on a Windows registry value.
///
/// Sourced from: `events/events/system/windows/registry_value.json`
#[derive(serde::Deserialize, serde::Serialize)]
pub struct RegistryValueActivity {
    pub activity_id: Option<crate::RegistryValueActivity>,
    /// The actor that performed the activity on the `reg_value` object.
    pub actor: String,
    pub prev_reg_value: Option<String>,
    pub reg_value: String,
}

impl RegistryValueActivity {
    pub const UID: u16 = 9;
}

// This file was automatically generated by ocsf-codegen at 2023-03-28T12:51:15+00:00 branch: "yaleman/issue9" link: <https://github.com/yaleman/ocsf-rs/commit/a19241f10710e7d5f5a476bfa2484030090763e4>
