//! OCSF crate, does Open Cyber Security Framework things.

//!

//! <h1><span color="red"> THIS IS VERY VERY VERY EARLY ALPHA</span></h1>

//!

//! The base schema is available at <https://ocsf.io>.

// This file was automatically generated by ocsf-codegen at 2025-02-08T00:22:36+00:00 branch: "more-fixes" link: <https://github.com/yaleman/ocsf-rs/commit/e3c933d060233d645bbfb4b9ab8f230ab9ba725e> OCSF Schema version: 1.2.0

//! This was the schema version that the code was generated from (1.2.0).

pub static OCSF_SCHEMA_VERSION: &str = "1.2.0";

pub mod categories;

pub mod dictionary;

pub mod objects;

pub mod profiles;

pub mod events;
