//! OCSF crate, does Open Cyber Security Framework things.

//!

//! <h1><span color="red"> THIS IS VERY VERY VERY EARLY ALPHA</span></h1>

//!

//! The base schema is available at <https://ocsf.io>.

// This file was automatically generated by ocsf-codegen at 2024-05-08T22:25:01+00:00 branch: "main" link: <https://github.com/yaleman/ocsf-rs/commit/e1a82e9b5299743a0c62bf0756f2eee94b7238a8> OCSF Schema version: 1.2.0

/// This was the schema version that the code was generated from (1.2.0).

pub static OCSF_SCHEMA_VERSION: &str = "1.2.0";

pub mod profiles;

pub mod events;

pub mod categories;

pub mod dictionary;

pub mod objects;
