//* hello world

// This file was automatically generated by ocsf-codegen at 2023-03-28T12:51:15+00:00 branch: "yaleman/issue9" link: <https://github.com/yaleman/ocsf-rs/commit/a19241f10710e7d5f5a476bfa2484030090763e4>
