//* hello world

// This file was automatically generated by ocsf-codegen at 2023-06-06T03:33:41+00:00 branch: "yaleman/issue9" link: <https://github.com/yaleman/ocsf-rs/commit/79a55e1a7e6ab3fdb662d961c59066a530e7afae>