//* hello world

// This file was automatically generated by ocsf-codegen at 2023-06-06T22:56:49+00:00 branch: "yaleman/issue9" link: <https://github.com/yaleman/ocsf-rs/commit/7c25539db4b4823979b3d4ee870fad2ab8f805cf>