//* I'm not saying it's the junk drawer, but it's also *not* *not* the junk drawer.

// This file was automatically generated by ocsf-codegen at 2023-03-19T00:43:59+00:00

/// This was the schema version that the code was generated from.

pub static OCSF_SCHEMA_VERSION: &str = "1.0.0-rc.2";
