//* OCSF Profiles

// This file was automatically generated by ocsf-codegen at 2023-03-29T11:20:41+00:00 branch: "yaleman/issue9" link: <https://github.com/yaleman/ocsf-rs/commit/e3cab7448ca160ea1e324c46692c5096b4c5b3fa>
