//* OCSF Profiles

// This file was automatically generated by ocsf-codegen at 2025-06-14T00:18:00+00:00 branch: "maintainer" link: <https://github.com/yaleman/ocsf-rs/commit/ad7e3fd9a25fbceee7f76850998ff9ed47df5372> OCSF Schema version: 1.2.0
