[package]
name = "ocsf-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.9", features = ["derive"] }
codegen = "0.2.0"
env_logger = "0.10.0"
log = "0.4.17"
serde_json = "1.0.94"
string_morph = "0.1.0"
walkdir = "2.3.3"

[[bin]]
name = "ocsf-codegen"
