// This file was automatically generated by ocsf-codegen at 2023-03-19T13:22:12+00:00

// kilroy was here audit.json

// kilroy was here access_activity.json

// kilroy was here entity.json

// kilroy was here api.json

pub enum Authorization {
    Unknown,
    /// Assign special privileges to a new logon.
    AssignPrivileges,
    /// Assign special groups to a new logon.
    AssignGroups,
    Other,
}

impl From<Authorization> for u8 {
    fn from(input: Authorization) -> u8 {
        match input {
            Authorization::Unknown => 0,
            Authorization::AssignPrivileges => 1,
            Authorization::AssignGroups => 2,
            Authorization::Other => 99,
        }
    }
}

impl TryFrom<u8> for Authorization {
    type Error = String;

    fn try_from(input: u8) -> Result<Self, String> {
        let res = match input {
            0 => Authorization::Unknown,
            1 => Authorization::AssignPrivileges,
            2 => Authorization::AssignGroups,
            99 => Authorization::Other,
            _ => return Err("invalid value".to_string()),
        };
        Ok(res)
    }
}

// kilroy was here authorization.json

// kilroy was here authentication.json

// kilroy was here account.json
