/// Device Inventory Info events report device inventory data.
///
/// Sourced from: `events/inventory/inventory_info.json`
#[derive(Deserialize, Serialize)]
pub struct InventoryInfo {
    device: Option<String>,
}

/// The Device Inventory/Configuration event is a generic event that defines a set of attributes available in the inventory/configuration events. As a generic event, it could be used to log events that are not otherwise defined by the Device Inventory/Configuration category.
///
/// Sourced from: `events/inventory/inventory.json`
#[derive(Deserialize, Serialize)]
pub struct Inventory {
    activity_id: Option<String>,
    device: String,
}

/// Device Config State events report device inventory data.
///
/// Sourced from: `events/inventory/config_state.json`
#[derive(Deserialize, Serialize)]
pub struct ConfigState {
    cis_benchmark_result: Option<String>,
}

use serde::{Deserialize, Serialize};

// This file was automatically generated by ocsf-codegen at 2023-03-27T21:46:59+00:00 branch: "yaleman/issue8" link: <https://github.com/yaleman/ocsf-rs/commit/4e69c4f97b90710c53906ab4e63de0c80aa8f60a>
