/// The Device Inventory/Configuration event is a generic event that defines a set of attributes available in the inventory/configuration events. As a generic event, it could be used to log events that are not otherwise defined by the Device Inventory/Configuration category.
///
/// Sourced from: `events/events/inventory/inventory.json`
#[derive(serde::Deserialize, serde::Serialize)]
pub struct Inventory {
    pub activity_id: Option<String>,
    pub device: String,
}

impl Inventory {
    /// Returns the UID of the event type (5000)
    pub fn uid() -> u16 {
        5000 // UID value of event 5000
    }
}

/// Device Inventory Info events report device inventory data.
///
/// Sourced from: `events/events/inventory/inventory_info.json`
#[derive(serde::Deserialize, serde::Serialize)]
pub struct InventoryInfo {
    pub device: Option<String>,
}

impl InventoryInfo {
    /// Returns the UID of the event type (1)
    pub fn uid() -> u16 {
        1 // UID value of event 1
    }
}

/// Device Config State events report device inventory data.
///
/// Sourced from: `events/events/inventory/config_state.json`
#[derive(serde::Deserialize, serde::Serialize)]
pub struct ConfigState {
    pub cis_benchmark_result: Option<String>,
}

impl ConfigState {
    /// Returns the UID of the event type (2)
    pub fn uid() -> u16 {
        2 // UID value of event 2
    }
}

// This file was automatically generated by ocsf-codegen at 2023-03-28T11:14:40+00:00 branch: "yaleman/issue8" link: <https://github.com/yaleman/ocsf-rs/commit/9d78df7466f9ac2dd533f1a5efdb53c8ce479741>
