//! Events Module for the OCSF crate

// This file was automatically generated by ocsf-codegen at 2023-03-19T13:22:12+00:00

pub mod network;

pub mod system;

pub mod audit;

pub mod findings;

pub mod inventory;

// kilroy was here base_event.json
